import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import MotionProvider from "./components/MotionProvider";
import { SITE_URL } from "./site";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  // Required so relative OG/Twitter image paths resolve to absolute URLs.
  // Without it Next.js falls back to localhost and social previews break.
  metadataBase: new URL(SITE_URL),
  title: "Mohammed Abdul Omer | CSE-AIML Engineer",
  description:
    "Portfolio of Mohammed Abdul Omer — CSE-AIML Engineer specialising in LLM fine-tuning, multi-agent systems, RAG pipelines, and MLOps. 10 production projects, 8 live deployments.",
  keywords: [
    "CSE-AIML Engineer",
    "AI Engineer",
    "ML Engineer",
    "LLM Fine-tuning",
    "RAG",
    "MLOps",
    "LangGraph",
    "CrewAI",
    "Generative AI",
    "Mohammed Abdul Omer",
    "Hyderabad",
  ],
  authors: [{ name: "Mohammed Abdul Omer", url: "https://github.com/MOHD-OMER" }],
  creator: "Mohammed Abdul Omer",
  alternates: {
    canonical: "/",
  },

  // Open Graph — controls how the link looks when shared on LinkedIn, WhatsApp, etc.
  // The image itself is generated by app/opengraph-image.js.
  openGraph: {
    title: "Mohammed Abdul Omer | CSE-AIML Engineer",
    description:
      "CSE-AIML Engineer building production-grade LLMs, RAG systems, multi-agent pipelines, and MLOps workflows — end-to-end and deployed.",
    url: SITE_URL,
    siteName: "Mohammed Abdul Omer Portfolio",
    locale: "en_US",
    type: "website",
  },

  // Twitter / X card
  twitter: {
    card: "summary_large_image",
    title: "Mohammed Abdul Omer | CSE-AIML Engineer",
    description:
      "CSE-AIML Engineer building production-grade LLMs, RAG systems, multi-agent pipelines, and MLOps workflows.",
    creator: "@mohdomer",
  },

  robots: {
    index: true,
    follow: true,
  },
};

// themeColor / colorScheme belong in the viewport export, not metadata.
// Keeping them in metadata makes Next.js drop them and log a build warning.
export const viewport = {
  themeColor: "#3b82f6",
  colorScheme: "dark",
  width: "device-width",
  initialScale: 1,
};

// Person structured data. Every value here already appears on the page — this
// just states it in a form search engines can attach to an entity rather than
// having to infer from prose.
const personJsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Mohammed Abdul Omer",
  jobTitle: "CSE-AIML Engineer",
  url: SITE_URL,
  email: "mailto:mohammedabdulomer99@gmail.com",
  address: {
    "@type": "PostalAddress",
    addressLocality: "Hyderabad",
    addressCountry: "IN",
  },
  alumniOf: {
    "@type": "CollegeOrUniversity",
    name: "Lords Institute of Engineering & Technology",
  },
  knowsAbout: [
    "Large Language Models",
    "Retrieval-Augmented Generation",
    "Multi-Agent Systems",
    "MLOps",
    "Computer Vision",
  ],
  sameAs: [
    "https://github.com/MOHD-OMER",
    "https://www.linkedin.com/in/mohammad-abdul-omer/",
    "https://huggingface.co/mohdomer",
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      {/*
        No manual <head>: next/font self-hosts Inter at build time, so
        preconnecting to fonts.googleapis.com / fonts.gstatic.com opened two
        connections that were never used.
      */}
      <body className="min-h-screen bg-dark text-text font-sans antialiased">
        {/* Keyboard users can jump the navbar instead of tabbing through it */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-lg focus:bg-blue-500 focus:px-4 focus:py-2 focus:text-sm focus:font-semibold focus:text-white"
        >
          Skip to content
        </a>

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }}
        />

        {/* Honours prefers-reduced-motion for every Framer Motion animation */}
        <MotionProvider>
          {/* Fixed Navbar */}
          <NavBar />

          {/* Page Content */}
          {/* pt-16 mobile / pt-24 desktop — hero never clipped by navbar */}
          <main id="main" className="pt-16 md:pt-24">
            {children}
          </main>

          <Footer />
        </MotionProvider>
      </body>
    </html>
  );
}
