import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import MotionProvider from "./components/MotionProvider";
import { SITE_URL } from "./site";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  // Required so relative OG/Twitter image paths resolve to absolute URLs.
  // Without it Next.js falls back to localhost and social previews break.
  metadataBase: new URL(SITE_URL),
  title: "Mohammed Abdul Omer | CSE-AIML Engineer",
  description:
    "Portfolio of Mohammed Abdul Omer — CSE-AIML Engineer specialising in LLM fine-tuning, multi-agent systems, RAG pipelines, and MLOps. 10 production projects, 8 live deployments.",
  keywords: [
    "CSE-AIML Engineer",
    "AI Engineer",
    "ML Engineer",
    "LLM Fine-tuning",
    "RAG",
    "MLOps",
    "LangGraph",
    "CrewAI",
    "Generative AI",
    "Mohammed Abdul Omer",
    "Hyderabad",
  ],
  authors: [{ name: "Mohammed Abdul Omer", url: "https://github.com/MOHD-OMER" }],
  creator: "Mohammed Abdul Omer",
  alternates: {
    canonical: "/",
  },

  // Open Graph — controls how the link looks when shared on LinkedIn, WhatsApp, etc.
  // The image itself is generated by app/opengraph-image.js.
  openGraph: {
    title: "Mohammed Abdul Omer | CSE-AIML Engineer",
    description:
      "CSE-AIML Engineer building production-grade LLMs, RAG systems, multi-agent pipelines, and MLOps workflows — end-to-end and deployed.",
    url: SITE_URL,
    siteName: "Mohammed Abdul Omer Portfolio",
    locale: "en_US",
    type: "website",
  },

  // Twitter / X card
  twitter: {
    card: "summary_large_image",
    title: "Mohammed Abdul Omer | CSE-AIML Engineer",
    description:
      "CSE-AIML Engineer building production-grade LLMs, RAG systems, multi-agent pipelines, and MLOps workflows.",
    creator: "@mohdomer",
  },

  robots: {
    index: true,
    follow: true,
  },
};

// themeColor / colorScheme belong in the viewport export, not metadata.
// Keeping them in metadata makes Next.js drop them and log a build warning.
export const viewport = {
  themeColor: "#3b82f6",
  colorScheme: "dark",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      {/*
        No manual <head>: next/font self-hosts Inter at build time, so
        preconnecting to fonts.googleapis.com / fonts.gstatic.com opened two
        connections that were never used.
      */}
      <body className="min-h-screen bg-dark text-text font-sans antialiased">
        {/* Honours prefers-reduced-motion for every Framer Motion animation */}
        <MotionProvider>
          {/* Fixed Navbar */}
          <NavBar />

          {/* Page Content */}
          {/* pt-16 mobile / pt-24 desktop — hero never clipped by navbar */}
          <main className="pt-16 md:pt-24">{children}</main>
        </MotionProvider>
      </body>
    </html>
  );
}
